export const AUTH = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",

  GET_CURRENT_USER_IN_DB: "GET_CURRENT_USER_IN_DB",
  CHECK_ACCESS_TOKEN_IS_ACTIVE: "CHECK_ACCESS_TOKEN_IS_ACTIVE",
  REMOVE_ERROR: "REMOVE_ERROR",
  UPDATE_AVATAR: "UPDATE_AVATAR",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  RESULT_CHANGE_PASSWORD: "RESULT_CHANGE_PASSWORD"
};

export const CONTROLL_APP = {
  UPDATE_DRAWER: "UPDATE_DRAWER",
};
