export const COLOR= {
  ROOT_COLOR_PURPLE: "#5B6CA8",
  ROOT_COLOR_PURPLE_LIGHT: "#AFB6DA",
  ROOT_COLOR_PURPLE_WHITE: "#E9EDF6",
  ROOT_COLOR_MAGENTA: "#DE3576",
  ROOT_COLOR_MAGENTA_LIGHT: "#F2689D",
  ROOT_COLOR_MAGENTA_WHITE: "#F391B7",
  ROOT_COLOR_CYAN: "#24A8AF",
  ROOT_COLOR_CYAN_LIGHT: "#6BD8DB",
  ROOT_COLOR_CYAN_WHITE: "#8ED9DD",
  ROOT_COLOR_ORANGE: "#F5B120",
  ROOT_COLOR_ORANGE_LIGHT: "#F1BE50",
  ROOT_COLOR_ORANGE_WHITE: "#EACA85",
  ROOT_COLOR_BLACK: "#1A1819",
  ROOT_COLOR_GRAY: "#4F5458",
  ROOT_COLOR_SMOOTH: "#6D7B81",
  ROOT_COLOR_WHITE: "#FAFBF7",

  WHITE: "#fff",
  BLACK: "#000",
  TRANSPARENT: "#00000000",
};


